collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CNAME
  - LICENSE
  - README.md
  - webpack.config.js
  - "*.lock"
  - "*.log"
